import dotenv from 'dotenv'
dotenv.config()

import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!

const supabase = createClient(supabaseUrl, supabaseAnonKey)

const tasks = [
  // STAGE 1: 6 Months Before - Research & Planning
  { stage_id: 1, visa_types: ['all'], title: 'Research visa requirements for your type', description: 'Understand eligibility, costs, and timeline', steps: JSON.stringify([{order:1,text:'Visit UK Home Office official website'},{order:2,text:'Download visa guide for your category'},{order:3,text:'List all requirements (documents, fees, timeline)'}]), deadline_days_before: 180, order_num: 1 },
  { stage_id: 1, visa_types: ['all'], title: 'Define your moving goals', description: 'Be clear on why you\'re moving and what success looks like', steps: JSON.stringify([{order:1,text:'Write 3 reasons why you want to move'},{order:2,text:'Research target UK cities (salaries, housing, lifestyle)'},{order:3,text:'Set rough timeline for departure'}]), deadline_days_before: 180, order_num: 2 },
  { stage_id: 1, visa_types: ['work', 'hpi', 'graduate'], title: 'Research UK job market in your field', description: 'Understand demand, salaries, sponsorship', steps: JSON.stringify([{order:1,text:'Visit LinkedIn and search roles in your field'},{order:2,text:'Note companies that sponsor visas (use visa sponsor database)'},{order:3,text:'Check average salaries for your role'}]), deadline_days_before: 170, order_num: 3 },
  { stage_id: 1, visa_types: ['study'], title: 'Research UK universities and programs', description: 'Shortlist schools and understand entry requirements', steps: JSON.stringify([{order:1,text:'Visit QS Rankings and research universities'},{order:2,text:'Check program requirements and fees'},{order:3,text:'Note IELTS/test score requirements'}]), deadline_days_before: 180, order_num: 4 },
  { stage_id: 1, visa_types: ['all'], title: 'Calculate cost of living by city', description: 'Budget for rent, food, transport in target cities', steps: JSON.stringify([{order:1,text:'Research rent prices on Rightmove.co.uk'},{order:2,text:'Calculate total monthly budget (housing, food, transport, utilities)'},{order:3,text:'Determine if savings/income is sufficient'}]), deadline_days_before: 170, order_num: 5 },
  { stage_id: 1, visa_types: ['all'], title: 'Start saving for move', description: 'Build emergency fund and visa costs', steps: JSON.stringify([{order:1,text:'Calculate total moving costs (visa fee, flights, deposits, setup)'},{order:2,text:'Set monthly savings target'},{order:3,text:'Open dedicated savings account if needed'}]), deadline_days_before: 165, order_num: 6 },

  // STAGE 2: 4-5 Months Before - Document Preparation
  { stage_id: 2, visa_types: ['all'], title: 'Check passport validity', description: 'Must be valid 6+ months beyond your stay', steps: JSON.stringify([{order:1,text:'Check expiry date'},{order:2,text:'If <6 months validity, plan renewal immediately'},{order:3,text:'Nigerian Immigration Service or Ministry of Interior'}]), deadline_days_before: 150, order_num: 1 },
  { stage_id: 2, visa_types: ['all'], title: 'Get or renew passport (if needed)', description: 'Processing takes 4-6 weeks', steps: JSON.stringify([{order:1,text:'Visit Nigerian Immigration Service/Ministry office'},{order:2,text:'Submit forms and required documents'},{order:3,text:'Pay fees (~₦35,000-50,000)'},{order:4,text:'Wait 4-6 weeks for processing'}]), deadline_days_before: 150, order_num: 2 },
  { stage_id: 2, visa_types: ['all'], title: 'Gather financial documents', description: 'Collect bank statements, proof of funds', steps: JSON.stringify([{order:1,text:'Check minimum fund requirement for your visa'},{order:2,text:'Gather 6 months of bank statements'},{order:3,text:'Get bank letter confirming balance'},{order:4,text:'Save copies as PDF'}]), deadline_days_before: 120, order_num: 3 },
  { stage_id: 2, visa_types: ['all'], title: 'Get police clearance certificate', description: 'Proves you have no criminal record', steps: JSON.stringify([{order:1,text:'Visit your state CID or police headquarters'},{order:2,text:'Fill application form'},{order:3,text:'Submit: national ID, address proof'},{order:4,text:'Pay fee (~₦5,000), wait 1-2 weeks'}]), deadline_days_before: 120, order_num: 4 },
  { stage_id: 2, visa_types: ['all'], title: 'Book medical exam (TB screening)', description: 'Required for all Nigerian visa applicants (~£300-400)', steps: JSON.stringify([{order:1,text:'Search "UKVI approved clinic Lagos/Abuja"'},{order:2,text:'Call and book appointment'},{order:3,text:'Bring passport and payment'},{order:4,text:'Clinic sends results directly to UKVI'}]), deadline_days_before: 90, order_num: 5 },
  { stage_id: 2, visa_types: ['work'], title: 'Begin job search with sponsoring companies', description: 'Target employers who sponsor international workers', steps: JSON.stringify([{order:1,text:'Use LinkedIn with visa sponsorship filter'},{order:2,text:'Apply to 20-30 roles per week'},{order:3,text:'Prepare strong CV and cover letters'},{order:4,text:'Research company visa sponsor licenses'}]), deadline_days_before: 120, order_num: 6 },
  { stage_id: 2, visa_types: ['study'], title: 'Prepare for IELTS/TOEFL exam', description: 'Most UK universities require IELTS 6.5+', steps: JSON.stringify([{order:1,text:'Enroll in IELTS/TOEFL prep course'},{order:2,text:'Study for 8-12 weeks'},{order:3,text:'Book exam date (allow 2-3 months buffer)'},{order:4,text:'Aim for 6.5+ on IELTS'}]), deadline_days_before: 150, order_num: 7 },
  { stage_id: 2, visa_types: ['all'], title: 'Organize key documents in folder', description: 'Create physical and digital copies of everything', steps: JSON.stringify([{order:1,text:'Create folder: Passport, birth cert, education certs'},{order:2,text:'Create folder: Financial docs, bank statements'},{order:3,text:'Create folder: Employment/offer letters'},{order:4,text:'Make digital backups (Google Drive, external drive)'}]), deadline_days_before: 100, order_num: 8 },

  // STAGE 2 continued: 2-3 Months Before - Applications
  { stage_id: 2, visa_types: ['work'], title: 'Receive and accept job offer', description: 'Secure employment sponsorship letter', steps: JSON.stringify([{order:1,text:'Negotiate final salary and start date'},{order:2,text:'Get written offer letter (must mention visa sponsorship)'},{order:3,text:'Request Certificate of Sponsorship (CoS) from employer'},{order:4,text:'Save all documents as PDFs'}]), deadline_days_before: 90, order_num: 9 },
  { stage_id: 2, visa_types: ['study'], title: 'Submit university applications', description: 'Apply to shortlisted universities', steps: JSON.stringify([{order:1,text:'Prepare personal statements'},{order:2,text:'Gather transcripts and references'},{order:3,text:'Submit applications by university deadlines'},{order:4,text:'Track submission confirmations'}]), deadline_days_before: 150, order_num: 10 },
  { stage_id: 2, visa_types: ['study'], title: 'Receive university offer and accept', description: 'Get acceptance letter for visa application', steps: JSON.stringify([{order:1,text:'Receive conditional or unconditional offer'},{order:2,text:'Meet any conditions (final exam results, etc)'},{order:3,text:'Accept offer and get Confirmation of Acceptance (CAS)'},{order:4,text:'Download and save CAS number'}]), deadline_days_before: 90, order_num: 11 },
  { stage_id: 2, visa_types: ['all'], title: 'Book language proficiency test (if needed)', description: 'Some visas require language proof', steps: JSON.stringify([{order:1,text:'Check if your visa requires language proof'},{order:2,text:'Book IELTS, TOEFL, or Trinity exam'},{order:3,text:'Sit exam and get results'},{order:4,text:'Save certificate as PDF'}]), deadline_days_before: 80, order_num: 12 },

  // STAGE 3: 1-2 Months Before - Final Logistics
  { stage_id: 3, visa_types: ['all'], title: 'Submit visa application online', description: 'Apply on UK Home Office website', steps: JSON.stringify([{order:1,text:'Go to visas-immigration.service.gov.uk'},{order:2,text:'Create account and start new application'},{order:3,text:'Fill in all personal and travel details'},{order:4,text:'Upload all documents (passport, CoS/CAS, bank statements, etc)'},{order:5,text:'Pay visa fee (£284-719 depending on type and processing speed)'}]), deadline_days_before: 60, order_num: 1 },
  { stage_id: 3, visa_types: ['all'], title: 'Book biometrics appointment', description: 'Fingerprints and photo at TLS center', steps: JSON.stringify([{order:1,text:'After submitting application, you\'ll get booking link'},{order:2,text:'Schedule appointment at TLS Lagos or Abuja'},{order:3,text:'Choose convenient date (aim for 2-3 weeks after application)'}]), deadline_days_before: 50, order_num: 2 },
  { stage_id: 3, visa_types: ['all'], title: 'Attend biometrics appointment', description: 'Give fingerprints and photos at TLS', steps: JSON.stringify([{order:1,text:'Attend appointment on scheduled date'},{order:2,text:'Bring passport and biometrics booking reference'},{order:3,text:'Give fingerprints and take digital photo'},{order:4,text:'Get receipt confirmation'}]), deadline_days_before: 40, order_num: 3 },
  { stage_id: 3, visa_types: ['all'], title: 'Monitor visa decision status', description: 'Check email and UKVI portal daily', steps: JSON.stringify([{order:1,text:'Visa decisions usually take 3-8 weeks after biometrics'},{order:2,text:'Check email daily for decision notification'},{order:3,text:'If approved: visa sticker will be in your passport'},{order:4,text:'If rejected: read refusal reasons carefully'}]), deadline_days_before: 35, order_num: 4 },
  { stage_id: 3, visa_types: ['all'], title: 'Book flights', description: 'Search and book tickets early for better prices', steps: JSON.stringify([{order:1,text:'Use Skyscanner, Google Flights, or airline sites'},{order:2,text:'Book 4-6 weeks before departure for best prices'},{order:3,text:'Typical cost: ₦150k-300k depending on dates'},{order:4,text:'Save booking confirmation and itinerary'}]), deadline_days_before: 35, order_num: 5 },
  { stage_id: 3, visa_types: ['all'], title: 'Book accommodation for arrival', description: 'Arrange housing for first weeks', steps: JSON.stringify([{order:1,text:'Book Airbnb for first 2-4 weeks (~£30-50/night)'},{order:2,text:'Location: near work, university, or city center'},{order:3,text:'Save confirmation and landlord contact'},{order:4,text:'For long-term: start flat hunting on Rightmove/Zoopla'}]), deadline_days_before: 30, order_num: 6 },
  { stage_id: 3, visa_types: ['all'], title: 'Notify your Nigerian bank', description: 'Prevent fraud blocks when using card abroad', steps: JSON.stringify([{order:1,text:'Visit bank branch or call customer service'},{order:2,text:'Inform them of UK move and travel dates'},{order:3,text:'Ask about international card usage and fees'},{order:4,text:'Request international transfer options'}]), deadline_days_before: 25, order_num: 7 },
  { stage_id: 3, visa_types: ['all'], title: 'Buy travel insurance', description: 'Covers medical, delays, lost luggage (~£20-50)', steps: JSON.stringify([{order:1,text:'Search insuremytrip.com, directtravel.com, or AXA'},{order:2,text:'Compare international travel insurance quotes'},{order:3,text:'Buy policy covering full trip duration'},{order:4,text:'Download and save policy documents and numbers'}]), deadline_days_before: 20, order_num: 8 },
  { stage_id: 3, visa_types: ['all'], title: 'Plan what to pack', description: 'Prepare packing list and luggage', steps: JSON.stringify([{order:1,text:'Research UK weather for arrival month'},{order:2,text:'Pack: Documents folder, passport, medications, phone chargers'},{order:3,text:'Pack: Formal clothes for work/interviews'},{order:4,text:'Bring adapter for UK Type G plugs (3 rectangular pins)'}]), deadline_days_before: 20, order_num: 9 },
  { stage_id: 3, visa_types: ['all'], title: 'Arrange transportation to airport', description: 'Plan how you\'ll get to Lagos/Abuja airport', steps: JSON.stringify([{order:1,text:'Book Uber or arrange ride 3-4 hours before flight'},{order:2,text:'Arrive at airport 3 hours before international flight'},{order:3,text:'Bring: ID, flight confirmation, luggage'},{order:4,text:'Check bag allowance for your airline'}]), deadline_days_before: 3, order_num: 10 },

  // STAGE 4: First 72 Hours in UK
  { stage_id: 4, visa_types: ['all'], title: 'Clear immigration and collect luggage', description: 'Arrive and enter the UK', steps: JSON.stringify([{order:1,text:'Queue at immigration desk'},{order:2,text:'Present passport and visa to officer'},{order:3,text:'Answer questions: purpose, duration, accommodation'},{order:4,text:'Collect luggage at baggage claim'}]), deadline_days_before: 0, order_num: 1 },
  { stage_id: 4, visa_types: ['all'], title: 'Get transport card/SIM for UK', description: 'Buy Oyster or contactless card + SIM card', steps: JSON.stringify([{order:1,text:'Buy Oyster card at Tube station or get contactless card option'},{order:2,text:'OR use Apple Pay/Google Pay/debit card (taps work too)'},{order:3,text:'Visit Tesco Mobile, O2, or EE shop for SIM card'},{order:4,text:'Buy SIM (~£3-5) and top up credit (~£10-20)'}]), deadline_days_before: 0, order_num: 2 },
  { stage_id: 4, visa_types: ['all'], title: 'Get to accommodation', description: 'Travel from airport to your first place', steps: JSON.stringify([{order:1,text:'From Heathrow: Take TFL Train Express (£16) or Tube (£3.40)'},{order:1,text:'From Gatwick: Take train or bus to city center'},{order:3,text:'Use Google Maps or Citymapper app for navigation'},{order:4,text:'Check in to Airbnb/accommodation'}]), deadline_days_before: 0, order_num: 3 },
  { stage_id: 4, visa_types: ['all'], title: 'Register with NHS (health service)', description: 'Essential for free UK healthcare', steps: JSON.stringify([{order:1,text:'Find nearest GP on NHS.uk'},{order:2,text:'Visit in person with ID and accommodation proof'},{order:3,text:'Fill registration form'},{order:4,text:'You\'re registered within 2 weeks'}]), deadline_days_before: -1, order_num: 4 },
  { stage_id: 4, visa_types: ['all'], title: 'Activate UK phone number and contact home', description: 'Let family know you\'ve arrived safely', steps: JSON.stringify([{order:1,text:'Activate SIM with new UK number'},{order:2,text:'Add credit/plan via top-up or auto-renew'},{order:3,text:'Send number to family on WhatsApp'},{order:4,text:'Set up WhatsApp, Telegram, or Messenger'}]), deadline_days_before: -1, order_num: 5 },
  { stage_id: 4, visa_types: ['all'], title: 'Open UK bank account', description: 'Visit high street bank with ID and proof of address', steps: JSON.stringify([{order:1,text:'Visit HSBC, Barclays, Natwest, or Lloyds branch'},{order:2,text:'Bring: Passport, visa, accommodation letter'},{order:3,text:'Complete application (20-30 mins)'},{order:4,text:'Debit card arrives in 5-7 days'}]), deadline_days_before: -1, order_num: 6 },
  { stage_id: 4, visa_types: ['all'], title: 'Get proof of address letter', description: 'Essential document for many UK services', steps: JSON.stringify([{order:1,text:'Ask Airbnb host or landlord for accommodation letter'},{order:2,text:'Should show: your name, address, dates of stay'},{order:3,text:'Get it on letterhead or email confirmation'},{order:4,text:'Print 3-5 copies (you\'ll use this many times)'}]), deadline_days_before: -2, order_num: 7 },
  { stage_id: 4, visa_types: ['all'], title: 'Rest and explore your neighborhood', description: 'Adjust to UK time and environment', steps: JSON.stringify([{order:1,text:'Sleep and adjust to new timezone'},{order:2,text:'Walk around your area, find local shops'},{order:3,text:'Buy essentials: phone chargers, toiletries, snacks'},{order:4,text:'Get to know nearby streets and landmarks'}]), deadline_days_before: -2, order_num: 8 },

  // STAGE 5: First 30 Days
  { stage_id: 5, visa_types: ['all'], title: 'Apply for National Insurance Number', description: 'Required to work in UK', steps: JSON.stringify([{order:1,text:'Visit Jobcentre Plus office nearest you'},{order:2,text:'Bring: Passport, visa, proof of address'},{order:3,text:'Get interview appointment (same or next week)'},{order:4,text:'NI number arrives by post 1-2 weeks later'}]), deadline_days_before: -7, order_num: 1 },
  { stage_id: 5, visa_types: ['work', 'hpi'], title: 'Start employment', description: 'Begin your job with proper visa', steps: JSON.stringify([{order:1,text:'Confirm start date with employer'},{order:2,text:'Complete right-to-work verification with HR'},{order:3,text:'Bring passport to first day'},{order:4,text:'Complete tax forms (P45 or P46)'}]), deadline_days_before: -10, order_num: 2 },
  { stage_id: 5, visa_types: ['study'], title: 'Register with university', description: 'Formal enrollment and orientation', steps: JSON.stringify([{order:1,text:'Attend university orientation/induction week'},{order:2,text:'Register at college or department'},{order:3,text:'Get student ID card'},{order:4,text:'Get university email and library access'}]), deadline_days_before: -14, order_num: 3 },
  { stage_id: 5, visa_types: ['all'], title: 'Set up utilities if renting flat', description: 'Electricity, water, internet', steps: JSON.stringify([{order:1,text:'Electricity: Contact Octopus Energy, EDF, or British Gas'},{order:2,text:'Water: Usually included; check with landlord'},{order:3,text:'Internet: BT, Virgin, Plusnet, or Hyperoptic'},{order:4,text:'Provide meter readings and proof of address'}]), deadline_days_before: -14, order_num: 4 },
  { stage_id: 5, visa_types: ['all'], title: 'Buy British plug adapters', description: 'UK uses Type G plugs (3 rectangular pins)', steps: JSON.stringify([{order:1,text:'Buy from Currys, John Lewis, Poundland (£1-5)'},{order:2,text:'Get 2-3 adapters (bedroom, living room, office)'},{order:3,text:'Test with all your devices'}]), deadline_days_before: -20, order_num: 5 },
  { stage_id: 5, visa_types: ['all'], title: 'Find a permanent place to live', description: 'Flat hunt on Rightmove, Zoopla, SpareRoom', steps: JSON.stringify([{order:1,text:'Budget: £500-800/month for room or 1-bed'},{order:2,text:'View 5-10 properties in person'},{order:3,text:'Check: commute time, council tax, deposit requirements'},{order:4,text:'Sign tenancy agreement and pay deposit'}]), deadline_days_before: -21, order_num: 6 },
  { stage_id: 5, visa_types: ['all'], title: 'Join community and make friends', description: 'Build your support network', steps: JSON.stringify([{order:1,text:'Join Nigerian WhatsApp groups for your city'},{order:2,text:'Join Meetup.com groups (sports, hobbies, trivia)'},{order:3,text:'Attend work or university social events'},{order:4,text:'Visit church, mosque, or community center'}]), deadline_days_before: -21, order_num: 7 },

  // STAGE 6: Settling & Thriving
  { stage_id: 6, visa_types: ['all'], title: 'Get Oyster/contactless card for daily travel', description: 'Essential for London commuting', steps: JSON.stringify([{order:1,text:'If in London: Get Oyster card from TFL station'},{order:2,text:'OR use contactless debit card, Apple Pay, Google Pay'},{order:3,text:'Daily/weekly cost cap automatically applies'},{order:4,text:'Budget ~£50-100/month for transport'}]), deadline_days_before: -30, order_num: 1 },
  { stage_id: 6, visa_types: ['all'], title: 'Open savings account', description: 'Build emergency fund and credit history', steps: JSON.stringify([{order:1,text:'Open separate savings account at your bank'},{order:2,text:'Link to current account for easy transfers'},{order:3,text:'Aim to save 10-20% of monthly income'},{order:4,text:'Keep 3 months expenses as emergency fund'}]), deadline_days_before: -35, order_num: 2 },
  { stage_id: 6, visa_types: ['all'], title: 'Apply for credit card (build credit history)', description: 'Start building UK credit score', steps: JSON.stringify([{order:1,text:'Check eligibility on ClearScore or Experian'},{order:2,text:'Apply for student credit card (easier approval)'},{order:3,text:'Use for small purchases (£20-50/month)'},{order:4,text:'Pay in full every month (builds credit rating)'}]), deadline_days_before: -45, order_num: 3 },
  { stage_id: 6, visa_types: ['all'], title: 'Register with council (council tax, voting)', description: 'Complete civic registration', steps: JSON.stringify([{order:1,text:'Visit local council website or office'},{order:2,text:'Register for council tax band (if applicable)'},{order:3,text:'Register to vote if eligible'},{order:4,text:'Register for local services and benefits'}]), deadline_days_before: -45, order_num: 4 },
  { stage_id: 6, visa_types: ['all'], title: 'Explore your city and UK culture', description: 'Get to know your new home', steps: JSON.stringify([{order:1,text:'Walk around neighborhoods, find local cafes and shops'},{order:2,text:'Visit parks (all free in UK)'},{order:3,text:'Explore nearby cities by train (£20-50)'},{order:4,text:'Visit museums (most free in London)'}]), deadline_days_before: -45, order_num: 5 },
  { stage_id: 6, visa_types: ['all'], title: 'Document your arrival (visa compliance)', description: 'Keep records for visa renewal or future status', steps: JSON.stringify([{order:1,text:'Save all UK documents: tenancy, bank statements, council tax'},{order:2,text:'Take photos of accommodation and neighborhood'},{order:3,text:'Keep NHS registration, employer letters, etc'},{order:4,text:'Create backup folder in Google Drive'}]), deadline_days_before: -45, order_num: 6 },
]

async function seed() {
  console.log('Seeding extended tasks...')
  
  // First delete existing tasks
  await supabase.from('tasks').delete().neq('stage_id', 0)
  
  try {
    for (const task of tasks) {
      await supabase.from('tasks').insert([task])
    }
    console.log('✅ Tasks seeded successfully')
  } catch (error) {
    console.error('❌ Error seeding:', error)
  }
}

seed()
